[project]
name = "kicad-lib-parse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.4",
    "sexpdata>=1.0.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
